const Produtow = [
  {
    id: 1,
    image: "/imgorc/pendente1.jpg",
    tipo: "Pendentes",
    preco: 10000,
    toggle: 0,
  },
  {
    id: 2,
    image: "/imgorc/pendente2.jpg",
    tipo: "Pendentes",
    preco: 1000,
    toggle: 0,
  },
  {
    id: 3,
    image: "/imgorc/abajur1.jpg",
    tipo: "Abajures",
    preco: 10000,
    toggle: 0,
  },
  {
    id: 4,
    image: "/imgorc/abajur2.jpg",
    tipo: "Abajures",
    preco: 1000,
    toggle: 0,
  },
  { id: 5, image: "/imgorc/cama1.jpg", tipo: "Camas", preco: 10000, toggle: 0 },
  {
    id: 6,
    image: "/imgorc/cama2.jpg",
    tipo: "Camas",
    preco: 100000,
    toggle: 0,
  },
  {
    id: 7,
    image: "/imgorc/abajur3.jpg",
    tipo: "Abajures",
    preco: 5000,
    toggle: 0,
  },
  {
    id: 8,
    image: "/imgorc/abajur4.jpg",
    tipo: "Abajures",
    preco: 8000,
    toggle: 0,
  },
  {
    id: 9,
    image: "/imgorc/abajur5.jpg",
    tipo: "Abajures",
    preco: 6000,
    toggle: 0,
  },
  {
    id: 10,
    image: "/imgorc/cama3.jpg",
    tipo: "Camas",
    preco: 1500,
    toggle: 0,
  },
  {
    id: 11,
    image: "/imgorc/cama4.jpg",
    tipo: "Camas",
    preco: 15000,
    toggle: 0,
  },
  {
    id: 12,
    image: "/imgorc/cama5.jpg",
    tipo: "Camas",
    preco: 150000,
    toggle: 0,
  },
  {
    id: 13,
    image: "/imgorc/pendente3.jpg",
    tipo: "Pendentes",
    preco: 8000,
    toggle: 0,
  },
  {
    id: 14,
    image: "/imgorc/pendente4.jpg",
    tipo: "Pendentes",
    preco: 150000,
    toggle: 0,
  },
  {
    id: 15,
    image: "/imgorc/pendente5.jpg",
    tipo: "Pendentes",
    preco: 9000,
    toggle: 0,
  },
];

export default Produtow;
